from __future__ import annotations

from typing import Any, Protocol

from id_doc_ocr.leave_audit.domain.async_status import CallbackStatus
from id_doc_ocr.leave_audit.domain.config import ConfigKind, ConfigSnapshot
from id_doc_ocr.leave_audit.domain.enums import LeaveAuditStatus
from id_doc_ocr.leave_audit.domain.models import LeaveAuditResult, LeaveAuditTask, LeaveReviewDecision
from id_doc_ocr.leave_audit.messaging.outbox import CallbackOutboxItem


class LeaveAuditRepository(Protocol):
    """Persistence port owned by Leave Audit Service.

    SQLite and PostgreSQL implementations share this port. The service layer
    must not depend on a concrete database driver.
    """

    def save_task(self, task: LeaveAuditTask) -> None: ...

    def get_task(self, request_id: str) -> LeaveAuditTask | None: ...

    def list_tasks(self, status: str | None = None) -> list[LeaveAuditTask]: ...

    def update_task_status(self, request_id: str, status: LeaveAuditStatus) -> None: ...

    def update_callback_status(self, request_id: str, status: CallbackStatus) -> None: ...

    def save_result(self, result: LeaveAuditResult) -> None: ...

    def get_result(self, request_id: str) -> LeaveAuditResult | None: ...

    def save_review(self, decision: LeaveReviewDecision) -> None: ...

    def list_reviews(self, request_id: str) -> list[LeaveReviewDecision]: ...

    def stats(self) -> dict[str, int]: ...

    def get_field_mappings(self) -> dict[str, list[str]]: ...

    def save_field_mapping(self, canonical_field: str, candidates: list[str]) -> None: ...

    def get_rule_configs(self) -> list[dict[str, Any]]: ...

    def get_rule_config(self, leave_type: str) -> dict[str, Any] | None: ...

    def save_rule_config(self, leave_type: str, prompt_text: str, rules: list[dict[str, Any]], enabled: bool = True) -> None: ...

    def get_prompt_configs(self) -> list[dict[str, Any]]: ...

    def get_effective_prompt_texts(self, recognition_type: str) -> dict[str, str]: ...

    def save_prompt_config(self, recognition_type: str, prompt_type: str, prompt_text: str, enabled: bool = True) -> None: ...

    def save_config_snapshot(self, snapshot: ConfigSnapshot) -> None: ...

    def get_config_snapshot(self, version_id: str) -> ConfigSnapshot | None: ...

    def list_config_snapshots(self, kind: ConfigKind | None = None) -> list[ConfigSnapshot]: ...

    def apply_ocr_result(self, *, consumer_name: str, event_id: str, result: LeaveAuditResult, callback_payload: dict[str, Any] | None = None) -> bool: ...

    def list_pending_callbacks(self, limit: int = 100) -> list[CallbackOutboxItem]: ...

    def mark_callback_processing(self, callback_id: str) -> None: ...

    def mark_callback_succeeded(self, callback_id: str, request_id: str) -> None: ...

    def mark_callback_failed(self, callback_id: str, request_id: str, error: str, dead: bool = False) -> None: ...
